theme = "gruvbox"

[editor]
mouse = true
auto-pairs = false

line-number = "relative"
cursorline = false
color-modes = true
whitespace.render = "all"
#indent-guides.render = true

#[editor.whitespace.render]
#newline = "all"
#space = "none"
#tab = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
H = "goto_line_start"
L = "goto_line_end_newline"

[keys.select]
H = "goto_line_start"
L = "goto_line_end_newline"
