[language-server.typst-lsp]
command = "typst-lsp"
config = { exportPdf = "never" }

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []
language-servers = [ "typst-lsp" ]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[grammar]]
name = "typst"
source = { path = "/home/luis/data/tree-sitter-typst" }


[language-server.wgsl-lsp]
command = "wgsl_analyzer"

[[language]]
name = "wgsl"
language-servers = [ "wgsl-lsp" ]
