[[language]]
name = "wgsl"
language-server = { command = "wgsl_analyzer", args = [] }


[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []
#formatter = { command = "typst-fmt" , args = [] }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[grammar]]
name = "typst"
source = { path = "/home/luis/data/tree-sitter-typst" }

[[language-servers.typst-lsp]]
command = "typst-lsp"